'use strict';

module.exports = {
  'GET/': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/account': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/authAttempts': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/backups': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/change-password/{id}': ['root', 'admin'],
  'GET/clinician': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/dashboard': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/docs': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/docs/css/{path*}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/env': ['root', 'admin'],
  'GET/events': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/events/name/{name}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/events/user/{userId}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/feedback': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/feedback/{id}': ['root', 'admin'],
  'GET/forgot': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/invite': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/invite/create': ['root', 'admin', 'researcher', 'clinician'],
  'GET/invite/edit/{id}': ['root', 'admin'],
  'GET/invite/{id}': ['root', 'admin', 'researcher', 'analyst', 'clincian'],
  'GET/login': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/logout': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/participation': ['root', 'admin', 'researcher'],
  'GET/public/{param*}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/reset': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/roles': ['root', 'admin', 'researcher'],
  'GET/sessions': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/setup': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/signup': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/tokens': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/tokens/create': ['root', 'admin', 'researcher'],
  'GET/tokens/{id}': ['root', 'admin', 'researcher'],
  'GET/users': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/users/create': ['root', 'admin', 'researcher'],
  'GET/users/{id}': ['root', 'admin'],
  'GET/users/clinicians/{id}': ['root', 'admin'],
  'GET/api': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/auth-attempts': ['root', 'admin', 'researcher'],
  'GET/api/auth-attempts/{id}': ['admin'],
  'GET/api/backups': ['root', 'admin', 'researcher'],
  'GET/api/backups/refresh': ['root', 'admin'],
  'GET/api/clinicians': ['root', 'admin', 'researcher'],
  'GET/api/clinicians/my': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/env': ['root', 'admin'],
  'GET/api/env/{name}': ['root', 'admin'],
  'GET/api/events': ['root', 'admin', 'researcher'],
  'GET/api/events/name/{name}': ['root', 'admin', 'researcher'],
  'GET/api/events/user/{userId}': ['root', 'admin', 'researcher'],
  'GET/api/feedback': ['root', 'admin', 'researcher'],
  'GET/api/feedback/unresolved': ['root', 'admin', 'researcher'],
  'GET/api/feedback/{id}': ['root', 'admin', 'researcher'],
  'GET/api/invite': ['root', 'admin', 'researcher'],
  'GET/api/invite/{id}': ['root', 'admin', 'researcher'],
  'GET/api/select2/clinicians': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/select2/users': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/sessions': ['root', 'admin', 'researcher'],
  'GET/api/sessions/my': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/sessions/{id}': ['root', 'admin', 'researcher'],
  'GET/api/table/auth-attempts': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/backups': ['root', 'admin', 'researcher'],
  'GET/api/table/clinicians': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/clinicians/{id}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/events': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/feedback': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/invite': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/sessions': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/tokens': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/table/users': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/tokens': ['root', 'admin', 'researcher'],
  'GET/api/users': ['root', 'admin', 'researcher'],
  'GET/api/users/my': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'GET/api/users/{id}': ['admin'],
  'DELETE/api/auth-attempts/{id}': ['root','admin'],
  'DELETE/api/backups/{id}': ['root','admin'],
  'DELETE/api/clinicians/{id}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'DELETE/api/clinicians/{userId}/{clinicianId}': ['root', 'admin', 'researcher'],
  'DELETE/api/events/{id}': ['root','admin'],
  'DELETE/api/feedback/{id}': ['root','admin'],
  'DELETE/api/invite/{id}': ['root', 'admin', 'researcher'],
  'DELETE/api/sessions/{id}': ['root','admin'],
  'DELETE/api/sessions/my/{id}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'DELETE/api/tokens/{id}': ['root','admin'],
  'DELETE/api/users/{id}': ['root','admin'],
  'DELETE/api/users/{role}/{id}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'DELETE/api/logout': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/setup': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/available': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/backups': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/backups/internal': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/contact': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/events/{name}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/env': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/feedback': ['root', 'admin'],
  'POST/api/invite': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/login': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/login/forgot': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/login/reset': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/login/token': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/signup': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/tokens': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'POST/api/users': ['root','admin','researcher'],
  'PUT/api/backups/{id}': ['root','admin'],
  'PUT/api/clinicians/{id}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'PUT/api/clinicians/{userId}/{clinicianId}': ['root','admin','researcher'],
  'PUT/api/feedback/{id}': ['root', 'admin', 'researcher'],
  'PUT/api/invite/{id}': ['root', 'admin', 'researcher'],
  'PUT/api/invite/{id}/reject': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'PUT/api/tokens/{id}': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'PUT/api/users/my/password': ['root', 'admin', 'researcher', 'analyst', 'clinician'],
  'PUT/api/users/{id}': ['admin'],
  'PUT/api/users/{id}/participation': ['root', 'admin', 'researcher'],
  'PUT/api/users/{id}/password': ['root','admin'],
  'PUT/api/users/{role}/{id}': ['root', 'admin', 'researcher', 'analyst', 'clinician']
};

