name: deploy
on:
  push:
    branches:
      - 221-XHN-dev
  pull_request:
    branches:
      - 221-XHN-dev

jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Verify Docker Image
        uses: docker/build-push-action@v3
        if: github.ref != 'refs/heads/221-XHN-dev'
        with:
          push: false
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: github.ref == 'refs/heads/docker'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Build
        uses: docker/build-push-action@v3
        if: github.ref == 'refs/heads/221-XHN-dev'
        with:
          push: true
          tags: hicsail/anchor:unstable
      - name: Push to Staging
        uses: fjogeleit/http-request-action@v1
        if: github.ref == 'refs/heads/docker'
        with:
          method: "POST"
          url: ${{ secrets.PORTAINER_WEBHOOK }}

